version: '2'
services:
  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_URL: "mongo/comments"
      PORT: "3000"
      NODE_ENV: "production"
  mongo:
    image: mongo