# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
revisionHistoryLimit: 1
image:
  repository: registry.ng.bluemix.net/robert_namespace/mern-example
  tag: v1
  pullPolicy: IfNotPresent
service:
  name: Node
  type: NodePort
  containerPort: 3000
  env: production
services:
  mongo:
     url: mongo
     name: comments
