# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: mean
  tag: 1.0.0 
  pullPolicy: IfNotPresent
service:
  name: Node
  type: NodePort
  containerPort: 3000
services:
  mongo:
     url: mongodb://mongo:27017
